root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/bot ./cmd/bot"
  bin = "./tmp/bot"
  include_ext = ["go", "toml"]
  exclude_dir = ["tmp", "vendor", "mocks"]
  delay = 1000

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
