// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/arrowwhi/books_review_bot/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBookService is a mock of BookService interface.
type MockBookService struct {
	ctrl     *gomock.Controller
	recorder *MockBookServiceMockRecorder
	isgomock struct{}
}

// MockBookServiceMockRecorder is the mock recorder for MockBookService.
type MockBookServiceMockRecorder struct {
	mock *MockBookService
}

// NewMockBookService creates a new mock instance.
func NewMockBookService(ctrl *gomock.Controller) *MockBookService {
	mock := &MockBookService{ctrl: ctrl}
	mock.recorder = &MockBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookService) EXPECT() *MockBookServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBookService) Add(ctx context.Context, userID int64, input AddBookInput) (*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, userID, input)
	ret0, _ := ret[0].(*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBookServiceMockRecorder) Add(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBookService)(nil).Add), ctx, userID, input)
}

// Delete mocks base method.
func (m *MockBookService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBookService) GetByID(ctx context.Context, id int64) (*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBookService) List(ctx context.Context, userID int64, status domain.BookStatus, page int) (*BookList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, page)
	ret0, _ := ret[0].(*BookList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBookServiceMockRecorder) List(ctx, userID, status, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookService)(nil).List), ctx, userID, status, page)
}

// MoveToRead mocks base method.
func (m *MockBookService) MoveToRead(ctx context.Context, id int64) (*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToRead", ctx, id)
	ret0, _ := ret[0].(*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveToRead indicates an expected call of MoveToRead.
func (mr *MockBookServiceMockRecorder) MoveToRead(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToRead", reflect.TypeOf((*MockBookService)(nil).MoveToRead), ctx, id)
}

// Search mocks base method.
func (m *MockBookService) Search(ctx context.Context, userID int64, query string, page int) (*BookList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, userID, query, page)
	ret0, _ := ret[0].(*BookList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockBookServiceMockRecorder) Search(ctx, userID, query, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockBookService)(nil).Search), ctx, userID, query, page)
}

// Update mocks base method.
func (m *MockBookService) Update(ctx context.Context, id int64, input UpdateBookInput) (*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBookServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookService)(nil).Update), ctx, id, input)
}

// MockGenreService is a mock of GenreService interface.
type MockGenreService struct {
	ctrl     *gomock.Controller
	recorder *MockGenreServiceMockRecorder
	isgomock struct{}
}

// MockGenreServiceMockRecorder is the mock recorder for MockGenreService.
type MockGenreServiceMockRecorder struct {
	mock *MockGenreService
}

// NewMockGenreService creates a new mock instance.
func NewMockGenreService(ctrl *gomock.Controller) *MockGenreService {
	mock := &MockGenreService{ctrl: ctrl}
	mock.recorder = &MockGenreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreService) EXPECT() *MockGenreServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGenreService) Create(ctx context.Context, name string) (*domain.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(*domain.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGenreServiceMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGenreService)(nil).Create), ctx, name)
}

// List mocks base method.
func (m *MockGenreService) List(ctx context.Context) ([]*domain.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGenreServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGenreService)(nil).List), ctx)
}

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStatsService) Get(ctx context.Context, userID int64) (*domain.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*domain.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStatsServiceMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStatsService)(nil).Get), ctx, userID)
}

// MockRecommendService is a mock of RecommendService interface.
type MockRecommendService struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendServiceMockRecorder
	isgomock struct{}
}

// MockRecommendServiceMockRecorder is the mock recorder for MockRecommendService.
type MockRecommendServiceMockRecorder struct {
	mock *MockRecommendService
}

// NewMockRecommendService creates a new mock instance.
func NewMockRecommendService(ctrl *gomock.Controller) *MockRecommendService {
	mock := &MockRecommendService{ctrl: ctrl}
	mock.recorder = &MockRecommendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendService) EXPECT() *MockRecommendServiceMockRecorder {
	return m.recorder
}

// Recommend mocks base method.
func (m *MockRecommendService) Recommend(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommend", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockRecommendServiceMockRecorder) Recommend(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockRecommendService)(nil).Recommend), ctx, userID)
}

// MockReminderService is a mock of ReminderService interface.
type MockReminderService struct {
	ctrl     *gomock.Controller
	recorder *MockReminderServiceMockRecorder
	isgomock struct{}
}

// MockReminderServiceMockRecorder is the mock recorder for MockReminderService.
type MockReminderServiceMockRecorder struct {
	mock *MockReminderService
}

// NewMockReminderService creates a new mock instance.
func NewMockReminderService(ctrl *gomock.Controller) *MockReminderService {
	mock := &MockReminderService{ctrl: ctrl}
	mock.recorder = &MockReminderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderService) EXPECT() *MockReminderServiceMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockReminderService) Disable(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockReminderServiceMockRecorder) Disable(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockReminderService)(nil).Disable), ctx, userID)
}

// Get mocks base method.
func (m *MockReminderService) Get(ctx context.Context, userID int64) (*domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockReminderServiceMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReminderService)(nil).Get), ctx, userID)
}

// Set mocks base method.
func (m *MockReminderService) Set(ctx context.Context, userID int64, intervalDays int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, userID, intervalDays)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockReminderServiceMockRecorder) Set(ctx, userID, intervalDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockReminderService)(nil).Set), ctx, userID, intervalDays)
}

// Start mocks base method.
func (m *MockReminderService) Start(ctx context.Context, send func(int64, string)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, send)
}

// Start indicates an expected call of Start.
func (mr *MockReminderServiceMockRecorder) Start(ctx, send any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockReminderService)(nil).Start), ctx, send)
}
